### ISSUE TITLE
spamming my anilist with entire watch history

### ISSUE THREAD

**Issue by Amateur-God** [Beannsss/PlexAniSync#15]
Everytime this script pushes an update to anilist instead of just pushing whats updated it appears to be pushing my entire history, resulting in anilist having every show ive ever watched marked as watched again on the day the update is pushed

![image](https://github.com/bpwhelan/EmbyAniSync/assets/68581288/6490c155-4e8a-4188-ad78-c5f7fbf28dac)

this is the only script I'm using to sync to anilist so i don't think anything else could be causing this

**Comment by bpwhelan** [comment]
Hmm, not sure what to say, I really am unaware of how this would be an issue with my script. I've synced multiple users on my server for months and haven't seen a single case where it duplicates a log entry. Moreover, it will only push an update to a series when the EMBY watch count is higher than the Anilist watch count as described in this if else chain https://github.com/bpwhelan/EmbyAniSync/blob/99766d50117f819564c63c60accfa8d94889aa87/anilist.py#L719

**Comment by Amateur-God** [comment]
> Hmm, not sure what to say, I really am unaware of how this would be an issue with my script. I've synced multiple users on my server for months and haven't seen a single case where it duplicates a log entry. Moreover, it will only push an update to a series when the EMBY watch count is higher than the Anilist watch count as described in this if else chain
> 
> https://github.com/bpwhelan/EmbyAniSync/blob/99766d50117f819564c63c60accfa8d94889aa87/anilist.py#L719

so i disabled the script and left it disabled and had no issues with my entire watch history being resynced, however, once I re-enabled the script it started to happen again

**Comment by Amateur-God** [comment]
This appears to of been fixed by deleting the authorisation key and providing a new one in the env variables

**Comment by bpwhelan** [comment]
Going to go ahead and close this, I reviewed this and tried to get it to break for me but wasn't successful.
